[env]
TERM = "xterm-256color"

[general]
import = ["/home/shade/.config/alacritty/catppuccin-mocha.toml"]

[cursor]
blink_interval = 750
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 2000
multiplier = 1

[window]
dynamic_title = true
opacity = 1

[keyboard]
